//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace SilverlightMathPad.WCFMathPadSvc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HallOfFameEntry", Namespace="http://schemas.datacontract.org/2004/07/SilverlightMathPad.Web")]
    public partial class HallOfFameEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DateField;
        
        private string NameField;
        
        private string QuizTypeField;
        
        private int ScoreField;
        
        private string TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuizType {
            get {
                return this.QuizTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuizTypeField, value) != true)) {
                    this.QuizTypeField = value;
                    this.RaisePropertyChanged("QuizType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFMathPadSvc.IMathPadServices")]
    public interface IMathPadServices {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/AddEntryToHallOfFame", ReplyAction="http://tempuri.org/IMathPadServices/AddEntryToHallOfFameResponse")]
        System.IAsyncResult BeginAddEntryToHallOfFame(SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry, System.AsyncCallback callback, object asyncState);
        
        void EndAddEntryToHallOfFame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/GetEntriesOfHallOfFame", ReplyAction="http://tempuri.org/IMathPadServices/GetEntriesOfHallOfFameResponse")]
        System.IAsyncResult BeginGetEntriesOfHallOfFame(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> EndGetEntriesOfHallOfFame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/GetEntriesOfScoreBoard", ReplyAction="http://tempuri.org/IMathPadServices/GetEntriesOfScoreBoardResponse")]
        System.IAsyncResult BeginGetEntriesOfScoreBoard(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> EndGetEntriesOfScoreBoard(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/GetTopScore", ReplyAction="http://tempuri.org/IMathPadServices/GetTopScoreResponse")]
        System.IAsyncResult BeginGetTopScore(System.AsyncCallback callback, object asyncState);
        
        int EndGetTopScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/AddScoreBoard", ReplyAction="http://tempuri.org/IMathPadServices/AddScoreBoardResponse")]
        System.IAsyncResult BeginAddScoreBoard(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState);
        
        void EndAddScoreBoard(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathPadServices/AddHallofFame", ReplyAction="http://tempuri.org/IMathPadServices/AddHallofFameResponse")]
        System.IAsyncResult BeginAddHallofFame(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState);
        
        void EndAddHallofFame(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathPadServicesChannel : SilverlightMathPad.WCFMathPadSvc.IMathPadServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntriesOfHallOfFameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEntriesOfHallOfFameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntriesOfScoreBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEntriesOfScoreBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathPadServicesClient : System.ServiceModel.ClientBase<SilverlightMathPad.WCFMathPadSvc.IMathPadServices>, SilverlightMathPad.WCFMathPadSvc.IMathPadServices {
        
        private BeginOperationDelegate onBeginAddEntryToHallOfFameDelegate;
        
        private EndOperationDelegate onEndAddEntryToHallOfFameDelegate;
        
        private System.Threading.SendOrPostCallback onAddEntryToHallOfFameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEntriesOfHallOfFameDelegate;
        
        private EndOperationDelegate onEndGetEntriesOfHallOfFameDelegate;
        
        private System.Threading.SendOrPostCallback onGetEntriesOfHallOfFameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEntriesOfScoreBoardDelegate;
        
        private EndOperationDelegate onEndGetEntriesOfScoreBoardDelegate;
        
        private System.Threading.SendOrPostCallback onGetEntriesOfScoreBoardCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopScoreDelegate;
        
        private EndOperationDelegate onEndGetTopScoreDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddScoreBoardDelegate;
        
        private EndOperationDelegate onEndAddScoreBoardDelegate;
        
        private System.Threading.SendOrPostCallback onAddScoreBoardCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddHallofFameDelegate;
        
        private EndOperationDelegate onEndAddHallofFameDelegate;
        
        private System.Threading.SendOrPostCallback onAddHallofFameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MathPadServicesClient() {
        }
        
        public MathPadServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathPadServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathPadServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathPadServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddEntryToHallOfFameCompleted;
        
        public event System.EventHandler<GetEntriesOfHallOfFameCompletedEventArgs> GetEntriesOfHallOfFameCompleted;
        
        public event System.EventHandler<GetEntriesOfScoreBoardCompletedEventArgs> GetEntriesOfScoreBoardCompleted;
        
        public event System.EventHandler<GetTopScoreCompletedEventArgs> GetTopScoreCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddScoreBoardCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddHallofFameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginAddEntryToHallOfFame(SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddEntryToHallOfFame(objFameEntry, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndAddEntryToHallOfFame(System.IAsyncResult result) {
            base.Channel.EndAddEntryToHallOfFame(result);
        }
        
        private System.IAsyncResult OnBeginAddEntryToHallOfFame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry = ((SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry)(inValues[0]));
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginAddEntryToHallOfFame(objFameEntry, callback, asyncState);
        }
        
        private object[] OnEndAddEntryToHallOfFame(System.IAsyncResult result) {
            ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndAddEntryToHallOfFame(result);
            return null;
        }
        
        private void OnAddEntryToHallOfFameCompleted(object state) {
            if ((this.AddEntryToHallOfFameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddEntryToHallOfFameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddEntryToHallOfFameAsync(SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry) {
            this.AddEntryToHallOfFameAsync(objFameEntry, null);
        }
        
        public void AddEntryToHallOfFameAsync(SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry, object userState) {
            if ((this.onBeginAddEntryToHallOfFameDelegate == null)) {
                this.onBeginAddEntryToHallOfFameDelegate = new BeginOperationDelegate(this.OnBeginAddEntryToHallOfFame);
            }
            if ((this.onEndAddEntryToHallOfFameDelegate == null)) {
                this.onEndAddEntryToHallOfFameDelegate = new EndOperationDelegate(this.OnEndAddEntryToHallOfFame);
            }
            if ((this.onAddEntryToHallOfFameCompletedDelegate == null)) {
                this.onAddEntryToHallOfFameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddEntryToHallOfFameCompleted);
            }
            base.InvokeAsync(this.onBeginAddEntryToHallOfFameDelegate, new object[] {
                        objFameEntry}, this.onEndAddEntryToHallOfFameDelegate, this.onAddEntryToHallOfFameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginGetEntriesOfHallOfFame(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEntriesOfHallOfFame(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndGetEntriesOfHallOfFame(System.IAsyncResult result) {
            return base.Channel.EndGetEntriesOfHallOfFame(result);
        }
        
        private System.IAsyncResult OnBeginGetEntriesOfHallOfFame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginGetEntriesOfHallOfFame(callback, asyncState);
        }
        
        private object[] OnEndGetEntriesOfHallOfFame(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> retVal = ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndGetEntriesOfHallOfFame(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEntriesOfHallOfFameCompleted(object state) {
            if ((this.GetEntriesOfHallOfFameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEntriesOfHallOfFameCompleted(this, new GetEntriesOfHallOfFameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEntriesOfHallOfFameAsync() {
            this.GetEntriesOfHallOfFameAsync(null);
        }
        
        public void GetEntriesOfHallOfFameAsync(object userState) {
            if ((this.onBeginGetEntriesOfHallOfFameDelegate == null)) {
                this.onBeginGetEntriesOfHallOfFameDelegate = new BeginOperationDelegate(this.OnBeginGetEntriesOfHallOfFame);
            }
            if ((this.onEndGetEntriesOfHallOfFameDelegate == null)) {
                this.onEndGetEntriesOfHallOfFameDelegate = new EndOperationDelegate(this.OnEndGetEntriesOfHallOfFame);
            }
            if ((this.onGetEntriesOfHallOfFameCompletedDelegate == null)) {
                this.onGetEntriesOfHallOfFameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEntriesOfHallOfFameCompleted);
            }
            base.InvokeAsync(this.onBeginGetEntriesOfHallOfFameDelegate, null, this.onEndGetEntriesOfHallOfFameDelegate, this.onGetEntriesOfHallOfFameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginGetEntriesOfScoreBoard(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEntriesOfScoreBoard(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndGetEntriesOfScoreBoard(System.IAsyncResult result) {
            return base.Channel.EndGetEntriesOfScoreBoard(result);
        }
        
        private System.IAsyncResult OnBeginGetEntriesOfScoreBoard(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginGetEntriesOfScoreBoard(callback, asyncState);
        }
        
        private object[] OnEndGetEntriesOfScoreBoard(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> retVal = ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndGetEntriesOfScoreBoard(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEntriesOfScoreBoardCompleted(object state) {
            if ((this.GetEntriesOfScoreBoardCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEntriesOfScoreBoardCompleted(this, new GetEntriesOfScoreBoardCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEntriesOfScoreBoardAsync() {
            this.GetEntriesOfScoreBoardAsync(null);
        }
        
        public void GetEntriesOfScoreBoardAsync(object userState) {
            if ((this.onBeginGetEntriesOfScoreBoardDelegate == null)) {
                this.onBeginGetEntriesOfScoreBoardDelegate = new BeginOperationDelegate(this.OnBeginGetEntriesOfScoreBoard);
            }
            if ((this.onEndGetEntriesOfScoreBoardDelegate == null)) {
                this.onEndGetEntriesOfScoreBoardDelegate = new EndOperationDelegate(this.OnEndGetEntriesOfScoreBoard);
            }
            if ((this.onGetEntriesOfScoreBoardCompletedDelegate == null)) {
                this.onGetEntriesOfScoreBoardCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEntriesOfScoreBoardCompleted);
            }
            base.InvokeAsync(this.onBeginGetEntriesOfScoreBoardDelegate, null, this.onEndGetEntriesOfScoreBoardDelegate, this.onGetEntriesOfScoreBoardCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginGetTopScore(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopScore(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndGetTopScore(System.IAsyncResult result) {
            return base.Channel.EndGetTopScore(result);
        }
        
        private System.IAsyncResult OnBeginGetTopScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginGetTopScore(callback, asyncState);
        }
        
        private object[] OnEndGetTopScore(System.IAsyncResult result) {
            int retVal = ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndGetTopScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopScoreCompleted(object state) {
            if ((this.GetTopScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopScoreCompleted(this, new GetTopScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopScoreAsync() {
            this.GetTopScoreAsync(null);
        }
        
        public void GetTopScoreAsync(object userState) {
            if ((this.onBeginGetTopScoreDelegate == null)) {
                this.onBeginGetTopScoreDelegate = new BeginOperationDelegate(this.OnBeginGetTopScore);
            }
            if ((this.onEndGetTopScoreDelegate == null)) {
                this.onEndGetTopScoreDelegate = new EndOperationDelegate(this.OnEndGetTopScore);
            }
            if ((this.onGetTopScoreCompletedDelegate == null)) {
                this.onGetTopScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopScoreCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopScoreDelegate, null, this.onEndGetTopScoreDelegate, this.onGetTopScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginAddScoreBoard(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddScoreBoard(strName, intPoints, intTime, strAddition, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndAddScoreBoard(System.IAsyncResult result) {
            base.Channel.EndAddScoreBoard(result);
        }
        
        private System.IAsyncResult OnBeginAddScoreBoard(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strName = ((string)(inValues[0]));
            int intPoints = ((int)(inValues[1]));
            int intTime = ((int)(inValues[2]));
            string strAddition = ((string)(inValues[3]));
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginAddScoreBoard(strName, intPoints, intTime, strAddition, callback, asyncState);
        }
        
        private object[] OnEndAddScoreBoard(System.IAsyncResult result) {
            ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndAddScoreBoard(result);
            return null;
        }
        
        private void OnAddScoreBoardCompleted(object state) {
            if ((this.AddScoreBoardCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddScoreBoardCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddScoreBoardAsync(string strName, int intPoints, int intTime, string strAddition) {
            this.AddScoreBoardAsync(strName, intPoints, intTime, strAddition, null);
        }
        
        public void AddScoreBoardAsync(string strName, int intPoints, int intTime, string strAddition, object userState) {
            if ((this.onBeginAddScoreBoardDelegate == null)) {
                this.onBeginAddScoreBoardDelegate = new BeginOperationDelegate(this.OnBeginAddScoreBoard);
            }
            if ((this.onEndAddScoreBoardDelegate == null)) {
                this.onEndAddScoreBoardDelegate = new EndOperationDelegate(this.OnEndAddScoreBoard);
            }
            if ((this.onAddScoreBoardCompletedDelegate == null)) {
                this.onAddScoreBoardCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddScoreBoardCompleted);
            }
            base.InvokeAsync(this.onBeginAddScoreBoardDelegate, new object[] {
                        strName,
                        intPoints,
                        intTime,
                        strAddition}, this.onEndAddScoreBoardDelegate, this.onAddScoreBoardCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMathPad.WCFMathPadSvc.IMathPadServices.BeginAddHallofFame(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddHallofFame(strName, intPoints, intTime, strAddition, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverlightMathPad.WCFMathPadSvc.IMathPadServices.EndAddHallofFame(System.IAsyncResult result) {
            base.Channel.EndAddHallofFame(result);
        }
        
        private System.IAsyncResult OnBeginAddHallofFame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strName = ((string)(inValues[0]));
            int intPoints = ((int)(inValues[1]));
            int intTime = ((int)(inValues[2]));
            string strAddition = ((string)(inValues[3]));
            return ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).BeginAddHallofFame(strName, intPoints, intTime, strAddition, callback, asyncState);
        }
        
        private object[] OnEndAddHallofFame(System.IAsyncResult result) {
            ((SilverlightMathPad.WCFMathPadSvc.IMathPadServices)(this)).EndAddHallofFame(result);
            return null;
        }
        
        private void OnAddHallofFameCompleted(object state) {
            if ((this.AddHallofFameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddHallofFameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddHallofFameAsync(string strName, int intPoints, int intTime, string strAddition) {
            this.AddHallofFameAsync(strName, intPoints, intTime, strAddition, null);
        }
        
        public void AddHallofFameAsync(string strName, int intPoints, int intTime, string strAddition, object userState) {
            if ((this.onBeginAddHallofFameDelegate == null)) {
                this.onBeginAddHallofFameDelegate = new BeginOperationDelegate(this.OnBeginAddHallofFame);
            }
            if ((this.onEndAddHallofFameDelegate == null)) {
                this.onEndAddHallofFameDelegate = new EndOperationDelegate(this.OnEndAddHallofFame);
            }
            if ((this.onAddHallofFameCompletedDelegate == null)) {
                this.onAddHallofFameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddHallofFameCompleted);
            }
            base.InvokeAsync(this.onBeginAddHallofFameDelegate, new object[] {
                        strName,
                        intPoints,
                        intTime,
                        strAddition}, this.onEndAddHallofFameDelegate, this.onAddHallofFameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightMathPad.WCFMathPadSvc.IMathPadServices CreateChannel() {
            return new MathPadServicesClientChannel(this);
        }
        
        private class MathPadServicesClientChannel : ChannelBase<SilverlightMathPad.WCFMathPadSvc.IMathPadServices>, SilverlightMathPad.WCFMathPadSvc.IMathPadServices {
            
            public MathPadServicesClientChannel(System.ServiceModel.ClientBase<SilverlightMathPad.WCFMathPadSvc.IMathPadServices> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddEntryToHallOfFame(SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry objFameEntry, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = objFameEntry;
                System.IAsyncResult _result = base.BeginInvoke("AddEntryToHallOfFame", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddEntryToHallOfFame(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddEntryToHallOfFame", _args, result);
            }
            
            public System.IAsyncResult BeginGetEntriesOfHallOfFame(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetEntriesOfHallOfFame", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> EndGetEntriesOfHallOfFame(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry>)(base.EndInvoke("GetEntriesOfHallOfFame", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEntriesOfScoreBoard(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetEntriesOfScoreBoard", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> EndGetEntriesOfScoreBoard(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightMathPad.WCFMathPadSvc.HallOfFameEntry>)(base.EndInvoke("GetEntriesOfScoreBoard", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopScore(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTopScore", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetTopScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetTopScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddScoreBoard(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = strName;
                _args[1] = intPoints;
                _args[2] = intTime;
                _args[3] = strAddition;
                System.IAsyncResult _result = base.BeginInvoke("AddScoreBoard", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddScoreBoard(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddScoreBoard", _args, result);
            }
            
            public System.IAsyncResult BeginAddHallofFame(string strName, int intPoints, int intTime, string strAddition, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = strName;
                _args[1] = intPoints;
                _args[2] = intTime;
                _args[3] = strAddition;
                System.IAsyncResult _result = base.BeginInvoke("AddHallofFame", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddHallofFame(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddHallofFame", _args, result);
            }
        }
    }
}
